name: PR Auto Assign
on:
  pull_request:
    types: [opened, ready_for_review]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - uses: jimschubert/labeler-action@v2
        with:
          configuration-path: '.github/auto-assign-config.yml'